[package]
name = "monilib"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["staticlib", "cdylib", "lib"]

[dependencies]
boltffi = "0.29"
uuid = {  version = "1", features = ["serde", "v4", "v7"] }
serde_json = "1.0"
serde = { version = "1.0", features = ["derive", "rc"] }
tracing = "0.1"
tracing-subscriber = { version = "*", features = ["env-filter"] }
jiff = { version = "0.2.31", features = ["serde", "std"] }
enumset = "1.1"
log = "0.4.29"
rdxlib = { path = "../rdxlib"}

[dev-dependencies]
proptest = "1.11.0"
rstest = "0.26"
itertools = "0.15.0"
